function husky_lens_scan_objects () {
    huskylens.initMode(protocolAlgorithm.ALGORITHM_OBJECT_RECOGNITION)
    if (huskylens.isAppear_s(HUSKYLENSResultType_t.HUSKYLENSResultBlock)) {
        OLED.writeStringNewLine("Scanning ")
        OLED.drawLoading(0)
        music.playSoundEffect(music.createSoundEffect(WaveShape.Noise, 1272, 5000, 120, 183, 1253, SoundExpressionEffect.None, InterpolationCurve.Curve), SoundExpressionPlayMode.InBackground)
        OLED.drawLoading(16)
        huskylens.takePhotoToSDCard(HUSKYLENSphoto.PHOTO)
        OLED.drawLoading(22)
        huskylens.initI2c()
        OLED.drawLoading(38)
        huskylens.request()
        OLED.drawLoading(54)
        huskylens.writeLearn1(1)
        OLED.drawLoading(70)
        huskylens.writeName(1, "Popit")
        OLED.drawLoading(100)
        OLED.clear()
    } else {
        basic.showIcon(IconNames.Sad)
        basic.showString("There is a problem please press the restart button ")
        music.playMelody("C5 C C5 C C5 C C5 C ", 120)
    }
}
input.onButtonPressed(Button.A, function () {
    music.setBuiltInSpeakerEnabled(true)
})
input.onButtonPressed(Button.AB, function () {
    husky_lens_scan_objects()
})
input.onButtonPressed(Button.B, function () {
    music.setBuiltInSpeakerEnabled(false)
})
OLED.drawLoading(0)
OLED.writeStringNewLine("Hello")
OLED.drawLoading(10)
OLED.writeStringNewLine("Loading")
OLED.drawLoading(20)
OLED.newLine()
OLED.drawLoading(30)
OLED.clear()
OLED.drawLoading(40)
radio.setGroup(88)
OLED.drawLoading(50)
radio.setTransmitPower(7)
OLED.drawLoading(60)
radio.setFrequencyBand(31)
OLED.drawLoading(70)
music.setBuiltInSpeakerEnabled(true)
OLED.drawLoading(80)
music.startMelody(music.builtInMelody(Melodies.Nyan), MelodyOptions.ForeverInBackground)
OLED.drawLoading(90)
OLED.writeStringNewLine(" Banana")
OLED.drawLoading(100)
OLED.clear()
